# Generated by Django 5.0.6 on 2024-06-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Usuario')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
        ),
    ]
